# https://github.com/arc-community/arc/blob/master/.pre-commit-config.yaml
# https://github.com/pre-commit/pre-commit-hooks
# https://pre-commit.ci/
# pre-commit and pyproject.toml
# https://github.com/pre-commit/pre-commit/issues/1165#issuecomment-862603032
---
exclude: 'build|stubs'

default_language_version:
  python: python3

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: check-ast
  - id: check-merge-conflict
  - id: check-added-large-files
    args: ['--maxkb=500']
  - id: end-of-file-fixer
  - id: detect-private-key
  - id: mixed-line-ending
  - id: fix-encoding-pragma
    args: ['--remove']
...
