# https://github.com/mala-project/mala/blob/develop/.github/workflows/gh-pages.yml
# https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-first-deployment-with-github_token
---
name: docs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-docstrings:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -qU pydocstyle

      - name: Check docstrings
        run: pydocstyle --ignore "D104" app #--convention=numpy mutual exclusive

  build-and-deploy-pages:
    needs: test-docstrings
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 0 fetches complete history and tags

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt

      - name: Build docs
        run: |
          make -C docs
          sphinx-build -W --keep-going -b html \
            -d docs/_build/doctrees docs/source docs/_build/html
          mv -v docs/_build/html public

      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
...
